# Makefile.in generated by automake 1.7.9 from Makefile.am.
# plugins/Makefile.  Generated from Makefile.in by configure.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Makefile.am for the SASL plugins
# Rob Siemborski
# Rob Earhart
# $Id: Makefile.am,v 1.78.2.1 2009/04/27 17:58:26 murch Exp $
#
################################################################
# Copyright (c) 2000 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer. 
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The name "Carnegie Mellon University" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. For permission or any other legal
#    details, please contact  
#      Office of Technology Transfer
#      Carnegie Mellon University
#      5000 Forbes Avenue
#      Pittsburgh, PA  15213-3890
#      (412) 268-4387, fax: (412) 268-7395
#      tech-transfer@andrew.cmu.edu
#
# 4. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Computing Services
#     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
#
# CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
# THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
# FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
################################################################
#
#
# Copyright (c) 2010, Yahoo! Inc.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may 
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. 
# See accompanying LICENSE file for terms.
#
#
#


srcdir = .
srcdir = ..

pkgdatadir = $(datadir)/cyrus-sasl
pkglibdir = $(libdir)/cyrus-sasl
pkgincludedir = $(includedir)/cyrus-sasl
top_builddir = .

am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_triplet = i686-pc-linux-gnu
ACLOCAL = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run aclocal-1.7 -I $(top_srcdir)/cmulocal -I $(top_srcdir)/config
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run tar
AUTOCONF = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run autoconf
AUTOHEADER = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run autoheader
AUTOMAKE = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run automake-1.7
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -Wall -W -g
CMU_LIB_SUBDIR = lib
CPP = gcc -E
CPPFLAGS =  
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = deps
DIRS = 
DMALLOC_LIBS = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = grep -E
EXEEXT = 
GETADDRINFOOBJS = 
GETNAMEINFOOBJS = 
GETSUBOPT = 
GSSAPIBASE_LIBS =  -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -lresolv
GSSAPI_LIBS = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
IPCTYPE = unix
JAVAC = true
JAVADOC = true
JAVAH = true
JAVAROOT = 
JAVA_FALSE = 
JAVA_INCLUDES = 
JAVA_TRUE = #
LDFLAGS = 
LIBOBJS = 
LIBS = -lresolv -lresolv  
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_CRYPT = -lcrypt
LIB_DES = -lcrypto
LIB_DOOR = 
LIB_LDAP = 

LIB_MYSQL = 
LIB_PGSQL = 
LIB_SOCKET = -lresolv 
LIB_SQLITE = 
LN_S = ln -s
LTGETADDRINFOOBJS = 
LTGETNAMEINFOOBJS = 
LTLIBOBJS = 
LTSNPRINTFOBJS = 
MACOSX_FALSE = 
MACOSX_TRUE = #
MAKEINFO = ${SHELL} /homes/wmills/sasl/cyrus-sasl-2.1.23/config/missing --run makeinfo
NM = /usr/bin/nm -B
NO_SASL_DB_MANS_FALSE = 
NO_SASL_DB_MANS_TRUE = #
NTLM_LIBS = 
OBJEXT = o
OTP_LIBS = -lcrypto 
PACKAGE = cyrus-sasl
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_VERSION = 
PASSDSS_LIBS = 
PATH_SEPARATOR = :
PLAIN_LIBS = -lcrypt
PURECOV = 
PURIFY = 
PWCHECKMETH = 
PWCHECK_FALSE = 
PWCHECK_TRUE = #
RANLIB = ranlib
SAMPLE_FALSE = 
SAMPLE_TRUE = #
SASLAUTHD_FALSE = #
SASLAUTHD_TRUE = 
SASL_DB_BACKEND = db_berkeley.lo
SASL_DB_BACKEND_STATIC = db_berkeley.o allockey.o
SASL_DB_INC = 
SASL_DB_LIB =  -ldb-4.3
SASL_DB_MANS = saslpasswd2.8 sasldblistusers2.8
SASL_DB_UTILS = saslpasswd2 sasldblistusers2
SASL_DL_LIB = -ldl
SASL_KRB_LIB = 
SASL_MECHS =  libsasldb.la libcrammd5.la libdigestmd5.la libotp.la libgssapiv2.la libplain.la liboauth.la libanonymous.la liboauth_validate.la liboauth_new.la
SASL_STATIC_LIBS = 
SASL_STATIC_OBJS =  gssapi.o
SASL_STATIC_SRCS =  ../plugins/gssapi.c
SASL_UTIL_HEADERS_EXTRA = 
SASL_UTIL_LIBS_EXTRA = 
SET_MAKE = 
SFIO_INC_FLAGS = 
SFIO_LIB_FLAGS = 
SHELL = /bin/sh
SMTPTEST_PROGRAM = 
SNPRINTFOBJS = 
SRP_LIBS = 
STRIP = 
VERSION = 2.1.23
ac_ct_CC = gcc
ac_ct_RANLIB = ranlib
ac_ct_STRIP = 
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
configdir = /usr/lib/sasl2:/etc/sasl2
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /homes/wmills/sasl/cyrus-sasl-2.1.23/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include

plugindir = /usr/lib/sasl2
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
subdirs =  saslauthd
sysconfdir = ${prefix}/etc
target = i686-pc-linux-gnu
target_alias = 
target_cpu = i686
target_os = linux-gnu
target_vendor = pc

# Library version info - here at the top, for sanity
# CURRENT:REVISION:AGE
oauth_version = 2:23:0
oauth_new_version = 2:23:0
oauth_validate_version = 2:23:0


# INCLUDES = -I$(top_srcdir)/include -I$(top_srcdir)/lib -I$(top_srcdir)/sasldb -I$(top_builddir)/include
INCLUDES = -I/usr/include/sasl
AM_LDFLAGS = -module -export-dynamic -rpath $(plugindir)

COMPAT_OBJS =   

# EXTRA_DIST = makeinit.sh NTMakefile
EXTRA_DIST = 
# noinst_SCRIPTS = makeinit.sh
noinst_SCRIPTS = 

common_sources = plugin_common.c plugin_common.h

sasldir = $(prefix)/lib/sasl2
sasl_LTLIBRARIES =  liboauth.la liboauth_validate.la liboauth_new.la
EXTRA_LTLIBRARIES = liboauth.la liboauth_validate.la liboauth_new.la 


liboauth_la_SOURCES = oauth.c oauth_init.c $(common_sources)
liboauth_la_LDFLAGS = -version-info $(oauth_version)
liboauth_la_DEPENDENCIES = $(COMPAT_OBJS)
liboauth_la_LIBADD = $(PLAIN_LIBS) $(COMPAT_OBJS) -lssl -lcurl -ljansson

liboauth_new_la_SOURCES = oauth_new.c oauth_new_init.c $(common_sources)
liboauth_new_la_LDFLAGS = -version-info $(oauth_new_version)
liboauth_new_la_DEPENDENCIES = $(COMPAT_OBJS)
liboauth_new_la_LIBADD = $(PLAIN_LIBS) $(COMPAT_OBJS) -lssl -lcurl -ljansson

liboauth_validate_la_SOURCES = oauth_validate.c oauth_validate_init.c $(common_sources)
liboauth_validate_la_LDFLAGS = -version-info $(oauth_validate_version)
liboauth_validate_la_DEPENDENCIES = $(COMPAT_OBJS)
liboauth_validate_la_LIBADD = $(PLAIN_LIBS) $(COMPAT_OBJS) -ljansson



# Instructions for making the _init files
init_src = oauth_init.c oauth_validate_init.c oauth_new.c 


#CLEANFILES = $(init_src)
CLEANFILES = 
subdir = plugins
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LTLIBRARIES = $(sasl_LTLIBRARIES)



am_liboauth_la_OBJECTS = oauth.lo oauth_init.lo $(am__objects_1)
liboauth_la_OBJECTS = $(am_liboauth_la_OBJECTS)
am_liboauth_new_la_OBJECTS = oauth_new.lo oauth_new_init.lo $(am__objects_1)
liboauth_new_la_OBJECTS = $(am_liboauth_new_la_OBJECTS)
am_liboauth_validate_la_OBJECTS = oauth_validate.lo oauth_validate_init.lo $(am__objects_1)
liboauth_validate_la_OBJECTS = $(am_liboauth_validate_la_OBJECTS)

SCRIPTS = $(noinst_SCRIPTS)


DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
DEP_FILES = 	./$(DEPDIR)/oauth.Plo ./$(DEPDIR)/oauth_init.Plo \
	./$(DEPDIR)/oauth_new.Plo ./$(DEPDIR)/oauth_new_init.Plo \
	./$(DEPDIR)/oauth_validate.Plo ./$(DEPDIR)/oauth_validate_init.Plo \


COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(libanonymous_la_SOURCES) $(libcrammd5_la_SOURCES) \
	$(libdigestmd5_la_SOURCES) $(libgssapiv2_la_SOURCES) \
	$(libkerberos4_la_SOURCES) $(libldapdb_la_SOURCES) \
	$(liblogin_la_SOURCES) $(libntlm_la_SOURCES) \
	$(liboauth_la_SOURCES) $(liboauth_new_la_SOURCES) $(liboauth_validate_la_SOURCES) $(libotp_la_SOURCES) \
	$(libpassdss_la_SOURCES) $(libplain_la_SOURCES) \
	$(libsasldb_la_SOURCES) $(libsql_la_SOURCES) \
	$(libsrp_la_SOURCES)
#DIST_COMMON = $(srcdir)/Makefile.in Makefile.am
DIST_COMMON = 
SOURCES = $(libanonymous_la_SOURCES) $(libcrammd5_la_SOURCES) $(libdigestmd5_la_SOURCES) $(libgssapiv2_la_SOURCES) $(libkerberos4_la_SOURCES) $(libldapdb_la_SOURCES) $(liblogin_la_SOURCES) $(libntlm_la_SOURCES) $(liboauth_la_SOURCES)  $(liboauth_new_la_SOURCES) $(liboauth_validate_la_SOURCES) $(libotp_la_SOURCES) $(libpassdss_la_SOURCES) $(libplain_la_SOURCES) $(libsasldb_la_SOURCES) $(libsql_la_SOURCES) $(libsrp_la_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
#$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#	cd $(top_srcdir) && \
#	  $(AUTOMAKE) --gnu  plugins/Makefile
#Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
#	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)
saslLTLIBRARIES_INSTALL = $(INSTALL)
install-saslLTLIBRARIES: $(sasl_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(sasldir)
	@list='$(sasl_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f="`echo $$p | sed -e 's|^.*/||'`"; \
	    echo " $(LIBTOOL) --mode=install $(saslLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(sasldir)/$$f"; \
	    $(LIBTOOL) --mode=install $(saslLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(sasldir)/$$f; \
	  else :; fi; \
	done

uninstall-saslLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(sasl_LTLIBRARIES)'; for p in $$list; do \
	    p="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(sasldir)/$$p"; \
	  $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(sasldir)/$$p; \
	done

clean-saslLTLIBRARIES:
	-test -z "$(sasl_LTLIBRARIES)" || rm -f $(sasl_LTLIBRARIES)
	@list='$(sasl_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" = "$$p" && dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done


liboauth.la: $(liboauth_la_OBJECTS) $(liboauth_la_DEPENDENCIES) 
	$(LINK)  $(liboauth_la_LDFLAGS) $(liboauth_la_OBJECTS) $(liboauth_la_LIBADD) $(LIBS)
liboauth_new.la: $(liboauth_new_la_OBJECTS) $(liboauth_new_la_DEPENDENCIES) 
	$(LINK)  $(liboauth_new_la_LDFLAGS) $(liboauth_new_la_OBJECTS) $(liboauth_new_la_LIBADD) $(LIBS)
liboauth_validate.la: $(liboauth_validate_la_OBJECTS) $(liboauth_validate_la_DEPENDENCIES) 
	$(LINK)  $(liboauth_validate_la_LDFLAGS) $(liboauth_validate_la_OBJECTS) $(liboauth_validate_la_LIBADD) $(LIBS)


mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/oauth.Plo
include ./$(DEPDIR)/oauth_init.Plo
include ./$(DEPDIR)/oauth_new.Plo
include ./$(DEPDIR)/oauth_new_init.Plo
include ./$(DEPDIR)/oauth_validate.Plo
include ./$(DEPDIR)/oauth_validate_init.Plo


.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `test -f '$<' || echo '$(srcdir)/'`$<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`

.c.lo:
	if $(LTCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Plo"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=yes \
#	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
#	$(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
uninstall-info-am:

ETAGS = etags
ETAGSFLAGS =

CTAGS = ctags
CTAGSFLAGS =

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$tags$$unique" \
	  || $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	     $$tags $$unique

ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkinstalldirs) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(SCRIPTS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(sasldir)
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-saslLTLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-saslLTLIBRARIES

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-info-am uninstall-saslLTLIBRARIES

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-saslLTLIBRARIES ctags distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-saslLTLIBRARIES install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-info-am \
	uninstall-saslLTLIBRARIES


# ${init_src}: $(srcdir)/makeinit.sh
#	$(SHELL) $(srcdir)/makeinit.sh

# Compatibility function build rules (they build in lib/)
$(COMPAT_OBJS):
	rm -f $(COMPAT_OBJS)
	cd ../lib; $(MAKE) $(COMPAT_OBJS)
	for file in $(COMPAT_OBJS); do ln -s ../lib/$$file .; done
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
